### ISSUE TITLE
languages list is caseSensitive

### ISSUE THREAD

**Issue by idandagan** [BelkaLab/language-cultures#3]
Hi,
I'm using the "getLanguageName" method, as part of a RESTful API that I'm building.

The problem is that the langCode param can be supplied in varies ways.
Such as:
en-us/en-Us/en-US/etc...
**But the getLanguageName function doesn't support inCaseSentsitive.**

What to you think about add this support?

The changes would be as the following:
1. Change the languages list obj to lowercase
2. In the function "getLanguageName" to add "langCode.toLowerCase() in _languages.languages"

I can create a PR for that if you agree.

**Comment by GiovanniFrigo** [comment]
I'm not really willing to transform language names in `languages.js` to lowercase, as I feel that right now we are using the correct/most common capitalization (see [this list](https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx)).

I could however force the correct capitalization on the getLanguageName input before looking it up on the table.

**Comment by GiovanniFrigo** [comment]
This issue is now fixed in v0.1.3

**Comment by idandagan** [comment]
Thanks GiovanniFrigo, this is great :)
